from flask import Flask, jsonify, request
import random
import time
import os

app = Flask(__name__)

@app.route("/api/v1", methods=["GET"])
def motion_handler():
    action = request.args.get("action")

    if action == "getCmd":
        record = {
            "id": random.randint(1000, 9999),
            "timestamp": int(time.time()),
            "base": random.randint(0, 180),
            "shoulder": random.randint(0, 90),
            "elbow": random.randint(0, 90),
            "wrist": random.randint(-45, 45),
            "duration_ms": random.randint(500, 1500),
            "note": "autogenerated dummy command"
        }
        return jsonify(record)

    elif action == "setCmd":
        return jsonify({"message": "Command inserted"})

    else:
        return jsonify({"error": "Invalid or missing 'action' parameter"}), 400

if __name__ == "__main__":
    port = int(os.environ.get("PORT", 5000))
    app.run(host="0.0.0.0", port=port)
